title: Sarah Duffy
description: >
  Ph.D. Candidate<br>
  Department of Economics<br>
  University of Oxford<br><br>
  <a href="Duffy_CV.pdf">CV</a> | <a href="https://www.economics.ox.ac.uk/people/sarah-duffy">Oxford Website</a><br>
  <a href="mailto:sarah.duffy@economics.ac.uk">Email</a> | <a href="https://uk.linkedin.com/in/sarah-duffy-9b525a1b6">LinkedIn</a>
  <br><br>
logo: photo.jpg
show_downloads: false
theme: jekyll-theme-minimal

