title: Sarah Duffy
description: >
  Ph.D. Candidate<br>
  Department of Economics<br>
  University of Oxford <br>
 [CV](#) | [Oxford Website](#)<br>
 [Email](#) | [LinkedIn](#) | [X (Twitter)](#)
logo: photo.jpg
show_downloads: false
theme: jekyll-theme-minimal
